[package]
name = "cap2seq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
rtshark = "2.4.0"

#[dependencies.rtshark]
#path = "../rtshark"
